### ISSUE TITLE
Rationalise "truthScore" and "vote" in voteRequest object

### ISSUE THREAD

**Issue by madanalogy** [bettersg/checkMate#227]
@sarge1989 what does "Rationalise" here mean? Communicate meaning behind the values? Or is this some kind of mental gymnastics using fancy math :")

**Comment by sarge1989** [comment]
@madanalogy paiseh this is unclear! Basically, the system was set up such that the voteRequests data schema only had the "vote" field, which was used to capture the numeric truth score. So the previous onChange handlers (onVoteRequestUpdate) were already set up to track that variable in the WhatsApp flow. I think @TY0018 added a truthScore field too, which she uses to capture the numeric truth score the checker selects. I suppose that was done because "vote" sounds ambigious (probably a legacy reason why I called it that). But because the rest of the system expects the numeric score to be in "vote", I added it back too in the following snippet in api.ts (app.patch("/checkers/:phoneNo/messages/:msgId/voteRequest").

`        await voteRequestDoc.ref.update({
        category: vote,
        votedTimestamp: Timestamp.fromDate(new Date()),
        vote: truthScore, //otherwise onVoteRequestUpdate won't work...TO REVIEW
        truthScore: truthScore,
      });`

So now we can have two courses of action:

- Rename "vote" as "truthScore" and migrate everything, as semantically that makes more sense. But with more changes come more testing.
- Or get rid of "truthScore" and continue using "vote", which means we don't need to change as much.
